### PR TITLE
A first try at some slides for our presentation on Wed.

### PR DESCRIPTION
**Pull request by jakeharding**
Figured this was an easy way to share and collaborate.  Take a look at the presentation in the docs folder and let me know what you think.  Feel free to make any changes you want.

### CODE REVIEW

**Comment by bparish628** [comment]
Did you mean the dev branch? There are lots of things in this that shouldn't be?

**Comment by jakeharding** [comment]
Yep sure did.

**Comment by bparish628** [comment]
Those slides look fine to me :smile:

**Comment by jakeharding** [comment]
Closing because we don't need the presentation in our repo.

**Pull request closed without merging**
